### ISSUE TITLE
Not Working (New install)

### ISSUE THREAD

**Issue by knatz-dev** [divinites/LatexEquationPreview#1]
**Settings File**
{
    "equation_foreground_color": "yellow",
    "equation_background_color": "white",
    "equation_inline_size": "45%",
    "equation_block_size": "60%",
    "auto_compile": true,
    "convert_binary": "C:/Program Files/ImageMagick-7.0.3-Q16/convert.exe",
    "pdflatex_binary": "C:/texlive/2015/bin/win32/pdflatex.exe",
    "debug": 1
}
**Console**
Exception in thread Thread-11:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "preview in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\LaTeX Equation Preview.sublime-package", line 113, in run
  File "helper in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\LaTeX Equation Preview.sublime-package", line 145, in to_phantom
TypeError: 'NoneType' object is not iterable
**Complication**
My test equation is not in the main tex file but in a chapter tex file

**Comment by divinites** [comment]
the equation could be anywhere, it does not matter.

in your case, the binary path should be `C:\\Program Files\\ImageMagick-7.0.3-Q16\\convert.exe` and `C:\\texlive\\2015\\bin\\win32\\pdflatex.exe`

please tell me if changing path solve your problem. Thanks.

**Comment by knatz-dev** [comment]
I have changed the paths but still not working with the same error message.

**Comment by divinites** [comment]
`'NoneType' object is not iterable` normally disappear when user update the settings and restart sublime text, since it shows that the plug-in cannot recognize the equation. So the mouse cursor should be put inside the equation, for example:

``` latex
\begin{equation}
(Cursor must be inside this range) ++++
\frac{V}{w_{T}(\hat{\theta})}-p-A=\frac{V}{w_{F}(\hat{\theta})}-\hat{\theta}%
-A,  \label{indifferent condition}
++++(Cursor must be inside this range)
\end{equation}%
```

Also, Have you got Ghostscript installed?

**Comment by divinites** [comment]
I just pushed an update, if it solves your problem, please let me know, thanks.

**Comment by knatz-dev** [comment]
I have not installed ghostscript and the latest push didn't fix it. I will look into installing ghostscript and get back to you soon.

**Comment by divinites** [comment]
Thanks. The lastest version (0.7.2) is to make sure that the program only runs when the cursor is inside an equation (either inline or block). So you will no longer see 

```
TypeError: 'NoneType' object is not iterable
```

Also,  for your information, the new [readme.md](https://github.com/divinites/LatexEquationPreview/blob/master/README.md) contains the information about ghostscript.

**Comment by knatz-dev** [comment]
Installed ghostscript and still not working get the following console message

LatexEquationPreview >>> not in the scope.

**Comment by divinites** [comment]
Hi, the plugin complains that your current cursor is not inside an equation. If it actually is, could you please tap <kbd>ctrl+alt+shift+p</kbd> inside an equation and paste the output here?

**Comment by knatz-dev** [comment]
text.tex.latex meta.function.environment.math.latex

**Comment by divinites** [comment]
I see, this is the problem then. my setting is "meta.environment.math.inline.dollar.latex" for inline equation and "meta.environment.math.block.be.latex" for block equation, I am not aware of other possible scopes. 

I can fix this, could you please tell me whether your equation is inline or block?

**Comment by knatz-dev** [comment]
These are the equations I have tried
$$\int_0^\infty e^{-x^2} dx=\frac{\sqrt{\pi}}{2}$$

\begin{equation}
    \frac{A}{B*9}
\end{equation}

\begin{equation}
\frac{V}{w_{T}(\hat{\theta})}-p-A=\frac{V}{w_{F}(\hat{\theta})}-\hat{\theta}%
-A,  \label{indifferent condition}
\end{equation}%

The last one above I got from you and is the one I used ctrl+alt+shift+p on.

**Comment by divinites** [comment]
Thanks, which plug-in you are using for latex syntax highlight, latexing, latex tools or others?

**Comment by knatz-dev** [comment]
latex tools

**Comment by divinites** [comment]
thanks, that's all info that I need at this moment, I will prepare a fix and push an update this evening.

**Comment by divinites** [comment]
I found the problem. It is because new sublime text implements latex+ syntax instead of default latex syntax. so the equations have a new scope named `meta.function.environment.math.latex` refer to sublimehq/Packages#340.

**Comment by divinites** [comment]
0.7.3 should fix your problem.

if you still encounter the same problem, please do not hesitate to re-open this issue.

**Comment by knatz-dev** [comment]
It's working now thanks
